### ISSUE TITLE
Need Help to use this API

### ISSUE THREAD

**Issue by gawhemant** [socrata/soda-php#17]
Hello,

I wanted to use this api to get data from following url,
https://data.melbourne.vic.gov.au/resource/qnjw-wgaj.json

index.php
```php
<?php
  require_once("socrata.php");

  $view_uid = "qnjw-wgaj";
  $root_url = "data.melbourne.vic.gov.au";
  $app_token = "u6ag0nMwTLhy3AyR3IS9fq5FA";
  $response = NULL;

  $id = array_get("id", $_POST);
  $nbbikes = array_get("nbbikes",$_POST);
  $nbemptydoc = array_get("nbemptydoc",$_POST);

  if($id != NULL && $nbbikes != NULL && $nbemptydoc != NULL) {
    // Create a new unauthenticated client
    $socrata = new Socrata($root_url, $app_token);

    $params = array("\$select" => "($id, $nbbikes, $nbemptydoc)");

    $response = $socrata->get($view_uid, $params);
  }
echo "response",$response;
?>
```

**Comment by allejo** [comment]
What issue are you facing or what isn't working?

**Comment by gawhemant** [comment]
response is null

**Comment by gawhemant** [comment]
How can I integrate this API with Google Maps API?

**Comment by marks** [comment]
@gawhemant can you debug/print your `$params` variable?

**Comment by chrismetcalf** [comment]
@gawhemant What is your intention with the `$id, $nbbikes, $nbemptydoc` variables? Are those column names, or values you want to filter with?

If you're trying to select out column names, remove the parens (`(...)`) wrapping those variables so that its just a string like "foo, bar, quo". If you want to use them to filter or query the dataset, check out the options for [filtering](https://dev.socrata.com/docs/filtering.html) or [SoQL queries](https://dev.socrata.com/docs/queries/).

**Comment by chrismetcalf** [comment]
@gawhemant Based on your question in https://github.com/socrata/discuss/issues/13, it looks like you were trying to do a `$select` query.

If you change your setup of the `$params` variable to be more like the following it should work:

```php
$params = array("\$select" => "id, nbbikes, nbemptydoc");
```

**Comment by gawhemant** [comment]
I wanted a way to integrate this api calls with Google map api to directly display the information on Maps

**Comment by chrismetcalf** [comment]
You should check out https://dev.socrata.com/consumers/examples/google-maps.html. It makes use of the Google Maps JavaScript API and the Socrata Open Data API.
